#!/bin/bash

sudo apt update
sudo apt install -y python3-pip git libc6-dev libtool tcl-dev libssl-dev
cd /tmp
git clone https://github.com/sqlcipher/sqlcipher.git && \
    cd sqlcipher && \
    ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto" && \
    make && \
    sudo make install && \
    sudo ldconfig -n /usr/local/lib || \
    echo "Error building sqlcipher"

pip3 install -r requirements.txt
